.TH SUBFUSE 1 2008-12-13 NCBI "NCBI Tools User's Manual"
.SH NAME
subfuse \- merge Genbank submissions
.SH SYNOPSIS
.B subfuse
[\|\fB\-\fP\|]
[\|\fB\-o\fP\ \fIfilename\fP\|]
[\|\fB\-p\fP\ \fIpath\fP\|]
[\|\fB\-x\fP\ \fIext\fP\|]
.SH DESCRIPTION
\fBsubfuse\fP is a utility to consolidate multiple Genbank submissions
into a single batch submission.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-o\fP\ \fIfilename\fP
Output file (\fBstdout\fP by default)
.TP
\fB\-p\fP\ \fIpath\fP
Path to files
.TP
\fB\-x\fP\ \fIext\fP
Input filename suffix (\fB.sqn\fP by default)
.SH SEE ALSO
.BR sequin (1).
.SH AUTHOR
The National Center for Biotechnology Information.
